Remove size_t redefinition
There is a build error when compiling lk2nd in Alpine Linux
environment:

 In file included from include/platform/debug.h:26,
                  from include/debug.h:31,
                  from target/msm8916/init.c:29:
 include/sys/types.h:41:23: error: conflicting types for 'size_t'
    41 | typedef unsigned long size_t;
       |                       ^~~~~~
 In file included from /usr/include/stddef.h:17,
                  from include/sys/types.h:27,
                  from include/platform/debug.h:26,
                  from include/debug.h:31,
                  from target/msm8916/init.c:29:
 /usr/include/bits/alltypes.h:43:24: note: previous declaration of 'size_t' was here
    43 | typedef unsigned _Addr size_t;
       |

This is related to musl-libc specific type sizes for 32-bit architectures.

Good thing is that we don't need to redefine size_t at all. We can assume
that it is always typedef-ed properly.